postgis:
  image: postgis-arm:latest   # a minha imagem postgis criada
  container_name: postgis
  restart: unless-stopped
  environment:
    POSTGRES_DB: gis
    POSTGRES_USER: gis
    POSTGRES_PASSWORD: gis
  volumes:
    - ./data/postgis:/var/lib/postgresql/data
  networks:
    - gisnet
